### ISSUE TITLE
bug: Enabling the 'Use Metric Measurements' checkbox in TFM settings has no effect

### ISSUE THREAD

**Issue by robin24** [jfayre/talking-flight-monitor#46] opened 2020-09-19 17:35 UTC
**Describe the bug**

Enabling the 'Use Metric Measurements' in TFM settings does not appear to have any effect on distance readings.

**To Reproduce**

1. In TFM settings, enable 'Use Metric Measurements'.
2. With a flight loaded in the sim, press the command key followed by C.

**Expected behavior**

TFM reads the closest city but reports the distance in Nautical Miles rather than Kilometers.

**additional information
 - OS: Windows 10
 - TFM version:TFM-Pre0.94  
 - Flight simulator in use: Prepar3D V5

**Comment by jfayre** [comment] 2020-09-19 17:42
This is by choice, since aircraft distance measurements are almost always given in nautical miles. I'll ask the group for a consensus on this one.

**Comment by jfayre** [comment] 2022-09-17 03:17
Duplicate of issue 96

**Closed** 2022-09-17 03:16 UTC
